// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kodep/jarvis/internal/oboobs"
)

// Injectors from wire.go:

func InitializeApp() (App, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return App{}, nil, err
	}
	logger, cleanup, err := ProvideLogger(config)
	if err != nil {
		return App{}, nil, err
	}
	client := ProvideMattermostClient(config)
	mainLogsHandler := provideLogsHandler(logger)
	boobsClient := oboobs.NewBoobsClient()
	buttsClient := oboobs.NewButtsClient()
	mainBoobsAndButtsHandler := boobsAndButtsHandler{
		Client: client,
		Boobs:  boobsClient,
		Butts:  buttsClient,
	}
	eventsHandler := provideEventsHandler(mainLogsHandler, config, mainBoobsAndButtsHandler)
	listener, cleanup2 := ProvideListener(logger, client, eventsHandler)
	app := ProvideApp(logger, client, listener)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
