// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kodep/jarvis/internal/oboobs"
)

// Injectors from wire.go:

func InitializeApp() (App, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return App{}, nil, err
	}
	logger, cleanup, err := ProvideLogger(config)
	if err != nil {
		return App{}, nil, err
	}
	client := ProvideMattermostClient(config)
	wsClient, err := ProvideMattermostWSClient(logger, config)
	if err != nil {
		cleanup()
		return App{}, nil, err
	}
	mainLogsHandler := provideLogsHandler()
	boobsClient := oboobs.NewBoobsClient()
	buttsClient := oboobs.NewButtsClient()
	mainBoobsAndButtsHandler := boobsAndButtsHandler{
		Boobs: boobsClient,
		Butts: buttsClient,
	}
	eventsHandler := provideEventsHandler(config, mainLogsHandler, mainBoobsAndButtsHandler)
	listener := ProvideListener(logger, client, wsClient, eventsHandler)
	app := ProvideApp(logger, client, listener)
	return app, func() {
		cleanup()
	}, nil
}
